name: Create new library packages

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Build app
        run: yarn --pure-lockfile && yarn build
        env:
          BUILD_CONCURRENCY: 5

      - name: Set NPM Token Action
        uses: filipstefansson/set-npm-token-action@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          name: 'reme3d2y'
          email: 'reme3d2y@gmail.com'
          token: '${{ secrets.PERMISSION_GITHUB_TOKEN }}'

      - name: Publish root package
        run: |
          yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}

      - name: Publish separate packages
        run: |
          yarn pub
        env:
          GITHUB_TOKEN: ${{ secrets.PERMISSION_GITHUB_TOKEN }}
